apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-java-springboot-basic
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-79-tenant/load-app-245f44fc-9067-477e-9d86-e0c93f5012c0/devfile-sample-java-springboot-basic@sha256:6ebad8caaa9d2b7470832a0f757ca2c6c3454ee0dcf8a54f0b155f78659c8007
        name: my-java-springboot
        resources: {}
status: {}
